In [3]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])


array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
import numpy as np
arr=np.array([ [1,2,3],[4,5,6],[7,8,9]],dtype=np.float64)


In [13]:
import numpy as np
arr1=np.array([[1.3,-2.6,3.5],[4.7,-5.1,6.5]])
np.abs(arr1)

array([[ 1.3, -2.6,  3.5],
       [ 4.7, -5.1,  6.5]])

In [5]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
arr2
print(arr1+arr2)
arr1+5

[[ 8 10 12]
 [14 16 18]]


array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([[4],[5],[6]])